[platformio]
default_envs = smart_safe

[env]
framework = arduino
platform = espressif32
monitor_speed = 115200

[env:smart_safe]
board = esp32dev
upload_port = COM3
monitor_port = COM3
build_src_filter =
  -<*>
  +<smart_safe_main.cpp>
lib_deps =
  mobizt/Firebase Arduino Client Library for ESP8266 and ESP32
  madhephaestus/ESP32Servo
  adafruit/Adafruit MPU6050
  adafruit/Adafruit Unified Sensor

[env:esp32_camera]
board = esp32cam
upload_port = COM4
monitor_port = COM4
monitor_dtr = 0
monitor_rts = 0
build_src_filter =
  -<*>
  +<esp32_camera_main.cpp>
  +<../esp32-cam/pametan_sef_camera/*.cpp>
build_flags =
  -D CAMERA_MODEL_AI_THINKER
